export type CanonicalIntent = "expense" | "income"

export type CanonicalCategoryKey =
  | "RENT"
  | "UTILITIES"
  | "DINING"
  | "GROCERIES"
  | "SHOPPING"
  | "CLOTHING"
  | "HEALTH_PERSONAL_CARE"
  | "FITNESS_SPORTS"
  | "EDUCATION"
  | "ENTERTAINMENT"
  | "SUBSCRIPTIONS"
  | "PHONE_MOBILE"
  | "TRANSPORT_LOCAL"
  | "FUEL"
  | "TRAVEL_FLIGHTS"
  | "GIFTS"
  | "TREATS"
  | "OTHER_EXPENSE"
  | "INCOME_BIZUM"
  | "INCOME_FREELANCE"
  | "INCOME_INVESTMENTS"
  | "INCOME_SALARY"
  | "INCOME_OTHER"
  | "INCOME_GIFTS_RECEIVED"

export interface CanonicalCategoryDefinition {
  canonicalKey: CanonicalCategoryKey
  intent: CanonicalIntent
  keywords: string[]
  merchants?: string[]
  negativeKeywords?: string[]
  amountHints?: {
    positive?: number
    negative?: number
  }
  minConfidence?: number
}

export const CANONICAL_CATEGORIES: CanonicalCategoryDefinition[] = [
  {
    canonicalKey: "RENT",
    intent: "expense",
    keywords: [
      "alquiler",
      "arrendamiento",
      "renta",
      "lloguer",
      "rent",
      "landlord",
      "lease",
      "loyer",
      "bail",
      "inmobiliaria",
    ],
    merchants: ["agence", "foncia", "nexity", "inmobiliaria", "syndic"],
    negativeKeywords: ["parking", "rent a car", "car rental"],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "UTILITIES",
    intent: "expense",
    keywords: [
      "factura",
      "facturas",
      "recibo",
      "recibos",
      "servicio",
      "servicios",
      "luz",
      "electricidad",
      "energia",
      "gas",
      "agua",
      "internet",
      "fibra",
      "wifi",
      "adsl",
      "box",
      "freebox",
      "comunidad",
      "mantenimiento",
      "taxe",
      "impots",
      "assurance habitation",
      "home insurance",
    ],
    merchants: [
      "edf",
      "engie",
      "totalenergies",
      "iberdrola",
      "endesa",
      "naturgy",
      "veolia",
      "suez",
      "orange",
      "free",
      "sfr",
      "bouygues",
      "movistar",
      "vodafone",
      "masmovil",
      "digi",
      "assurance",
      "maif",
      "macif",
      "axa",
      "allianz",
    ],
    negativeKeywords: ["netflix", "spotify", "disney", "hbo", "prime video"],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "DINING",
    intent: "expense",
    keywords: [
      "cafe",
      "cafeteria",
      "bar",
      "restaurante",
      "restaurant",
      "tapas",
      "brunch",
      "kebab",
      "pizzeria",
      "pizza",
      "sushi",
      "coffee",
      "bakery",
      "bistro",
      "boulangerie",
      "patisserie",
      "brasserie",
      "esmorzar",
      "dinar",
      "sopar",
    ],
    merchants: [
      "starbucks",
      "paul",
      "pret",
      "mcdonalds",
      "burger king",
      "kfc",
      "subway",
      "dunkin",
      "deliveroo",
      "uber eats",
      "justeat",
      "glovo",
    ],
    negativeKeywords: ["grocery", "groceries", "supermercado", "supermarket"],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "GROCERIES",
    intent: "expense",
    keywords: [
      "supermercado",
      "super",
      "compra",
      "compras",
      "mercado",
      "fruteria",
      "carniceria",
      "pescaderia",
      "groceries",
      "grocery",
      "supermarket",
      "supermarche",
      "courses",
      "queviures",
      "supermercat",
    ],
    merchants: [
      "carrefour",
      "alcampo",
      "mercadona",
      "lidl",
      "aldi",
      "dia",
      "eroski",
      "consum",
      "bonpreu",
      "caprabo",
      "franprix",
      "monoprix",
      "auchan",
      "leclerc",
      "intermarche",
      "casino",
      "picard",
    ],
    negativeKeywords: ["zara", "h&m", "ikea", "amazon", "aliexpress", "temu"],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "SHOPPING",
    intent: "expense",
    keywords: [
      "compra online",
      "tienda",
      "ecommerce",
      "retail",
      "marketplace",
      "pedido",
      "shopping",
      "store",
      "boutique",
      "magasin",
    ],
    merchants: ["amazon", "aliexpress", "temu", "ebay", "ikea", "fnac", "el corte ingles"],
    amountHints: { negative: 0.2 },
    minConfidence: 0.9,
  },
  {
    canonicalKey: "CLOTHING",
    intent: "expense",
    keywords: [
      "ropa",
      "camiseta",
      "pantalon",
      "zapatos",
      "zapatillas",
      "abrigo",
      "chaqueta",
      "sneakers",
      "clothes",
      "clothing",
      "apparel",
      "fashion",
      "vetements",
      "chaussures",
      "roba",
      "sabates",
    ],
    merchants: [
      "zara",
      "bershka",
      "pull&bear",
      "stradivarius",
      "h&m",
      "uniqlo",
      "decathlon",
      "nike",
      "adidas",
    ],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "HEALTH_PERSONAL_CARE",
    intent: "expense",
    keywords: [
      "farmacia",
      "medico",
      "doctor",
      "clinica",
      "hospital",
      "seguro medico",
      "dentista",
      "optica",
      "health",
      "clinic",
      "dental",
      "pharmacy",
      "pharmacie",
      "medecin",
      "hopital",
      "mutuelle",
      "salut",
      "farmacia",
      "peluqueria",
      "barber",
      "estetica",
      "spa",
      "masaje",
      "cosmetica",
      "skincare",
    ],
    merchants: ["doctolib", "boots", "sanitas", "adeslas", "dkv", "mutuelle"],
    negativeKeywords: ["gym", "fitness", "crossfit"],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "FITNESS_SPORTS",
    intent: "expense",
    keywords: [
      "gimnasio",
      "gym",
      "fitness",
      "entreno",
      "entrenamiento",
      "deporte",
      "sport",
      "yoga",
      "pilates",
      "crossfit",
      "natacion",
      "salle de sport",
      "gimnas",
      "running",
    ],
    merchants: ["basic-fit", "fitness park", "keepcool", "neoness", "strava", "decathlon"],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "EDUCATION",
    intent: "expense",
    keywords: [
      "curso",
      "cursos",
      "academia",
      "universidad",
      "matricula",
      "tuition",
      "school",
      "libro",
      "libros",
      "examen",
      "certificado",
      "formation",
      "ecole",
      "college",
      "masterclass",
    ],
    merchants: ["udemy", "coursera", "edx", "domestika", "kindle"],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "ENTERTAINMENT",
    intent: "expense",
    keywords: [
      "cine",
      "pelicula",
      "teatro",
      "concierto",
      "museo",
      "exposicion",
      "ocio",
      "entradas",
      "ticket",
      "tickets",
      "entertainment",
      "cinema",
      "movie",
      "concert",
      "musee",
      "gaming",
      "videojuego",
    ],
    merchants: ["ticketmaster", "dice", "fnac", "pathe", "ugc", "steam", "playstation", "xbox"],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "SUBSCRIPTIONS",
    intent: "expense",
    keywords: [
      "suscripcion",
      "subscription",
      "mensualidad",
      "membership",
      "plan mensual",
      "abonnement",
      "recurring",
      "monthly plan",
    ],
    merchants: [
      "netflix",
      "spotify",
      "disney",
      "hbo",
      "prime video",
      "youtube premium",
      "icloud",
      "google one",
      "dropbox",
      "chatgpt",
      "github",
      "notion",
      "canva",
      "strava",
    ],
    amountHints: { negative: 0.2 },
    minConfidence: 0.85,
  },
  {
    canonicalKey: "PHONE_MOBILE",
    intent: "expense",
    keywords: [
      "telefono",
      "telefonia",
      "movil",
      "linea",
      "recarga",
      "sim",
      "roaming",
      "forfait",
      "mobile",
      "cellular",
    ],
    merchants: ["orange", "free", "sfr", "bouygues", "movistar", "vodafone", "masmovil", "digi"],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "TRANSPORT_LOCAL",
    intent: "expense",
    keywords: [
      "uber",
      "cabify",
      "taxi",
      "metro",
      "bus",
      "tren",
      "tranvia",
      "tmb",
      "renfe",
      "sncf",
      "ratp",
      "navette",
      "commute",
      "transport",
      "transit",
    ],
    merchants: ["uber", "cabify", "bolt", "free now", "sncf", "renfe", "ratp", "tmb", "blablacar"],
    negativeKeywords: ["flight", "hotel", "airbnb", "booking"],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "FUEL",
    intent: "expense",
    keywords: ["gasolina", "gasoil", "diesel", "carburante", "fuel", "station service", "essence"],
    merchants: ["repsol", "cepsa", "bp", "shell", "totalenergies", "galp"],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "TRAVEL_FLIGHTS",
    intent: "expense",
    keywords: [
      "vuelo",
      "vuelos",
      "flight",
      "airline",
      "avion",
      "aeropuerto",
      "boarding",
      "equipaje",
      "viaje",
      "viajes",
      "travel",
      "trip",
      "hotel",
      "hostel",
      "booking",
      "airbnb",
      "expedia",
    ],
    merchants: [
      "ryanair",
      "easyjet",
      "vueling",
      "iberia",
      "air france",
      "klm",
      "lufthansa",
      "booking",
      "airbnb",
      "expedia",
      "hostelworld",
    ],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "GIFTS",
    intent: "expense",
    keywords: ["regalo", "regalos", "gift", "present", "cumpleanos", "aniversario", "cadeau"],
    merchants: ["interflora", "flowers", "floristeria"],
    amountHints: { negative: 0.2 },
  },
  {
    canonicalKey: "TREATS",
    intent: "expense",
    keywords: ["capricho", "antojo", "treat", "indulgence", "snack", "helado", "bubble tea", "boba"],
    amountHints: { negative: 0.2 },
    minConfidence: 1,
  },
  {
    canonicalKey: "OTHER_EXPENSE",
    intent: "expense",
    keywords: ["varios", "misc", "miscellaneous", "other", "otros", "otros gastos"],
    amountHints: { negative: 0.2 },
    minConfidence: 1,
  },
  {
    canonicalKey: "INCOME_BIZUM",
    intent: "income",
    keywords: ["bizum", "bizzum"],
    merchants: ["bizum"],
    amountHints: { positive: 0.3 },
    minConfidence: 0.9,
  },
  {
    canonicalKey: "INCOME_FREELANCE",
    intent: "income",
    keywords: [
      "freelance",
      "factura emitida",
      "invoice paid",
      "cliente",
      "consulting",
      "consultoria",
      "honorarios",
      "prestation",
    ],
    amountHints: { positive: 0.2 },
  },
  {
    canonicalKey: "INCOME_INVESTMENTS",
    intent: "income",
    keywords: [
      "dividendo",
      "dividend",
      "interest",
      "intereses",
      "yield",
      "cupon",
      "coupon",
      "inversion",
      "investment",
      "capital gains",
      "plusvalia",
    ],
    merchants: ["degiro", "interactive brokers", "revolut", "trading212", "etoro"],
    amountHints: { positive: 0.25 },
  },
  {
    canonicalKey: "INCOME_SALARY",
    intent: "income",
    keywords: [
      "nomina",
      "salary",
      "salario",
      "payroll",
      "pay slip",
      "salaire",
      "ipvf",
      "institut photovoltaique",
    ],
    merchants: ["ipvf"],
    amountHints: { positive: 0.3 },
  },
  {
    canonicalKey: "INCOME_OTHER",
    intent: "income",
    keywords: ["ingreso", "abono", "refund", "devolucion", "reembolso", "remboursement"],
    amountHints: { positive: 0.15 },
    minConfidence: 0.95,
  },
  {
    canonicalKey: "INCOME_GIFTS_RECEIVED",
    intent: "income",
    keywords: ["regalo recibido", "gift received", "regalo de", "donation received", "virement recu"],
    amountHints: { positive: 0.25 },
    minConfidence: 0.95,
  },
]
